// SPDX-License-Identifier: GPL-3.0-only
#ifndef RNETMSGBROKER_GLOBAL_H
#define RNETMSGBROKER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RNETMSGBROKER_LIBRARY)
#  define RNETMSGBROKER_EXPORT Q_DECL_EXPORT
#else
#  define RNETMSGBROKER_EXPORT Q_DECL_IMPORT
#endif

#endif // RNETMSGBROKER_GLOBAL_H
